// src/components/converter.tsx
/** @jsx h */
import { h, RenderableProps } from 'preact';
import { useState, useEffect } from 'preact/hooks';
import Label from 'components/label';
import Input from 'components/input-controlled';
import useFocus from 'hooks/useFocus';
import { round } from 'modules/formatter';
import type { Festival } from 'src/festivals';

type Props = {
  festival: Festival;
};
function Converter({ festival }: RenderableProps<Props>) {
  const inputEl = useFocus();
  const [value, setValue] = useState(0);

  useEffect(() => setValue(0), [festival.rate]);

  return (
    <main class="bg-white rounded shadow uppercase p-8">
      <Label
        htmlFor={`${festival.rate}`}
        source={festival.currency}
        target="EUR"
        rate={festival.rate}
      />

      <Input
        forwardRef={inputEl}
        id={`${festival.rate}`}
        value={round(value)}
        onChange={setValue}
      />

      <div class="h-px my-6 bg-indigo-600" />

      <Label
        htmlFor="euros"
        source="EUR"
        target={festival.currency}
        rate={1 / festival.rate}
      />
      <Input
        id="euros"
        value={round(value * festival.rate)}
        onChange={(value) => setValue(value / festival.rate)}
      />
    </main>
  );
}

export default Converter;

// src/lib/Converter.svelte
<script lang="ts">
  import type { Festival } from 'src/festival';
  import Label from './Label.svelte';

  export let festival: Festival;

  function round(value: number): number {
    return Math.round(value * 100) / 100;
  }

  function handleInput(e: Event) {
    const target = e.target as HTMLInputElement;
    value = target.valueAsNumber / festival.rate;
  }

  let value = 0;
  $: convertedValue = round(value * festival.rate);
</script>

<div class="bg-white rounded shadow uppercase p-8" aria-live="polite">
  <Label
    htmlFor={festival.currency}
    source={festival.currency}
    target="EUR"
    rate={festival.rate}
  />

  <input
    id={festival.currency}
    type="number"
    step={0.01}
    class="mt-3 input"
    bind:value
  />
  <hr class="h-px my-6 border-indigo-600" />

  <Label
    htmlFor="euros"
    source="EUR"
    target={festival.currency}
    rate={1 / festival.rate}
  />
  <input
    id="euros"
    type="number"
    step={0.01}
    class="mt-3 input"
    value={convertedValue}
    on:input={handleInput}
  />
</div>
