// src/App.tsx
/** @jsx h */
import { h } from 'preact';
import { useState } from 'preact/hooks';

import { FestivalsProvider } from 'context/festivals-context';
import { FestivalProvider } from 'context/festival-context';

import Converter from 'components/converter';
import Festivals from 'components/festivals';
import Header from 'components/header';

const App = () => {
  const [isOpen, openDrawer] = useState(false);

  return (
    <FestivalsProvider>
      <FestivalProvider>
        <Festivals display={isOpen} closeDrawer={() => openDrawer(false)} />
        <div class="flex flex-col lg:justify-center lg:h-full lg:max-w-lg mx-auto">
          <Header openDrawer={() => openDrawer(true)} />
          <Converter />
        </div>
      </FestivalProvider>
    </FestivalsProvider>
  );
};

export default App;

// src/App.svelte
<script lang="ts">
  import Header from './lib/Header.svelte';
  import Converter from './lib/Converter.svelte';
  import Form from './lib/Form.svelte';
  import { getFestivalFromSearchLocation } from './lib/utils';
  import './global.css';

  const festivalFromUrl = getFestivalFromSearchLocation(window.location.search);
</script>

<main class="flex flex-col lg:justify-center lg:h-full lg:max-w-lg m-auto">
  {#if festivalFromUrl}
    <Header title={festivalFromUrl.name} />
    <Converter festival={festivalFromUrl} />
  {:else}
    <Form />
  {/if}
</main>
